# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
    weight: 11
  - name: Experience
    url: /#experience #/
    weight: 12
  - name: Education
    url: /#education
    weight: 20
  - name: Skills
    url: /#skills
    weight: 20
  - name: Projects
    url: /#projects #/
    weight: 30
  - name: Papers
    url: papers/
    weight: 40

#  - name: Teaching
#    url: teaching/
#    